[package]
name = "aleo"
version = "0.2.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Aleo"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = [
    "rust/account",
    "wasm"
]

[lib]
path = "cli/lib.rs"

[[bin]]
name = "aleo"
path = "cli/main.rs"

[dependencies.anyhow]
version = "1.0"

[dependencies.clap]
version = "3.1"
features = ["derive"]

[dependencies.colored]
version = "2"

[dependencies.indexmap]
version = "1.9"
features = ["rayon", "serde"]

[dependencies.once_cell]
version = "1"

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.rand_chacha]
version = "0.3.0"
default-features = false

[dependencies.self_update]
version = "0.28"

[dependencies.serde]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.snarkvm]
#path = "../snarkVM"
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0a5f6f1"
features = ["aleo-cli", "circuit", "console", "parallel"]

[dependencies.thiserror]
version = "1.0"

[dependencies.tokio]
version = "1.5"
features = ["rt"]

[dependencies.warp]
version = "0.3"

[dependencies.ureq]
version = "2.5"
features = ["json"]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = true
